language: java
jdk:
- oraclejdk8
os:
- linux
script: mvn install -Pinstall-runtime
install:
- sudo add-apt-repository -y ppa:webupd8team/java
- sudo apt-get update -qq
- sudo apt-get install -y oracle-java8-installer
before_script:
- sudo apt-get update -qq
- sudo apt-get install -y rpm
- sudo apt-get install -y wget
- wget http://download-aws.ej-technologies.com/install4j/install4j_unix_6_0_1.tar.gz
- tar zxvf install4j_unix_6_0_1.tar.gz
- wget -O /home/travis/build/vedmalex/AsciidocFX/install4j6/jres/linux-amd64-1.8.0_40.tar.gz http://asciidocfx.com/jres/linux-amd64-1.8.0_40.tar.gz
- wget -O /home/travis/build/vedmalex/AsciidocFX/install4j6/jres/macosx-amd64-1.8.0_40.tar.gz http://asciidocfx.com/jres/macosx-amd64-1.8.0_40.tar.gz
- wget -O /home/travis/build/vedmalex/AsciidocFX/install4j6/jres/windows-amd64-1.8.0_40.tar.gz http://asciidocfx.com/jres/windows-amd64-1.8.0_40.tar.gz
- mvn clean
- mvn install4j:install-license
deploy:
  provider: releases
  api_key:
    secure: UtndggRAFKGkLYgf0YxG0HNOtzalTYRsKhQtiTQmEAywsbzit4nNVDmqlyOjL4RK+fWnFQ3E0ELh75YLjEBwdKY7jEYYTxVE014RFQxZMLOnah4hdJrnyI6fURo+72bx4zLkPWd5JLyaIkTQ2ufnHdX3aK0lt5qM/yL9vRfhYYBr8aLR9cR18N+fG8gv+zuQTYvxwg6mdrB5yzSxH+ZnAmP+T8NXwGZAYoUeyP6BkQ/+sE6bGb3dkhL5tH1rJHet/7IJ+aTyE+VkhyCbI2Kjf7G0PSouG+0hrBAMp1yLsiObjqK5P/zGNR9rnEH+B0FjkmnDjf9CxC4eRoHgnq/evhHUPPX2Heu5iHs17quCFUhFGjYgTOYDvRqDHf6wAl2zqkEMCivyBsCUR/iwebpPVzY7/dT71l9jSSrG6XhGntxQFjkG8L2rMXfglcg2tp39HxvO7POGXelPO6XKgD4AC5N4P1Au8quLfEMIk39ZlH0aVP7ciqQMCB09m5weQesQzb3moqDLiBzeHb96IVNIwqTEwv3Jw/ZrZpsDDxi5mOwYXMQWgXKnxHwWxVIg+2sMU5dtrnYFOSJ+XgHB6qkA7Wt7uwuoBBB0UrXyqhlLQEw3AIsH5i6j0XJj4RLUu9uprj3E0wAulzVedkSqTCHkTu+u8s17ZgjFG3As6QXWLlI=
  file:
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Mac.dmg
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Linux.tar.gz
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Linux_No_JRE.tar.gz
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Windows.exe
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Windows_i586.exe
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Windows_No_JRE.exe
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Windows_i586_No_JRE.exe
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Windows.zip
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Windows_i586.zip
    - /home/travis/build/vedmalex/AsciidocFX/target/media/AsciidocFX_Windows_No_JRE.zip
    - /home/travis/build/vedmalex/AsciidocFX/target/media/updates.xml
  on:
    tags: true
    all_branches: true
    repo: vedmalex/AsciidocFX
env:
  global:
    secure: x4NoL51Uq5eGy+qYR3R5ca5J16lXN+45EwcRTE3FBxzxN91vK6GrKW8sbjZLTXeEIjhn9X1IEe8A2ljh4fnkOtIGl2bVHm8KJPNWa/EKmCLZ7KjCzXtyI5743pb+IJpIyCaevwasTBGFvsrs3NOsV/zipk0nEu08VdqEvp7AsXE=
